<?php

namespace App\Domains\Automation\Handlers;

use App\Domains\Automation\Contracts\AutomationHandler;
use App\Domains\Automation\DTOs\AutomationContext;
use App\Domains\Automation\DTOs\AutomationResult;
use App\Domains\Banking\Enums\BankTransactionType;
use App\Domains\Banking\Models\BankTransaction;
use App\Domains\Banking\Services\ReconciliationService;
use App\Domains\Invoicing\Models\Invoice;
use App\Domains\Organizations\Enums\Permission;
use App\Support\Money;
use Illuminate\Support\Facades\Log;

/**
 * Assigns incoming payments to invoices where the QR reference leaves no doubt.
 *
 * This is the one automation in the set that touches the ledger, and it is
 * deliberately narrower than the existing auto-reconciliation: it accepts only
 * an exact structured reference that resolves to exactly one open invoice for
 * exactly the invoiced amount. No amount tolerance, no name similarity, no
 * "best guess". A QR reference is generated by us and printed on our own
 * invoice, so a hit is an identity, not a resemblance — and anything short of
 * that identity is left for a person.
 *
 * Writes, therefore off until switched on.
 */
class QrPaymentMatchingHandler implements AutomationHandler
{
    public function __construct(private readonly ReconciliationService $reconciliation) {}

    public function key(): string
    {
        return 'qr_payment_matching';
    }

    public function label(): string
    {
        return 'automation_qr_payment_matching';
    }

    public function description(): string
    {
        return 'automation_qr_payment_matching_desc';
    }

    public function writes(): bool
    {
        return true;
    }

    public function permission(): Permission
    {
        return Permission::BankingReconcile;
    }

    public function run(AutomationContext $context): AutomationResult
    {
        $transactions = BankTransaction::query()
            ->with('bankAccount')
            ->whereHas('bankAccount', fn ($q) => $q->where('organization_id', $context->organization->id))
            ->where('is_reconciled', false)
            ->where('type', BankTransactionType::Credit)
            ->whereNotNull('structured_reference')
            ->get();

        $matched = 0;
        $needsReview = [];

        foreach ($transactions as $transaction) {
            $reference = (string) $transaction->structured_reference;

            // invoices carries a unique index on (organization_id, qr_reference),
            // so a reference resolves to one invoice or to none.
            $invoice = Invoice::where('organization_id', $context->organization->id)
                ->where('qr_reference', $reference)
                ->open()
                ->first();

            if (! $invoice) {
                continue;
            }

            // The reference identifies the invoice; the amount confirms the
            // payment is complete. A short payment must stay with a person.
            if (Money::compare((string) $transaction->amount, (string) $invoice->total) !== 0) {
                $needsReview[] = __('app.automation_qr_amount_mismatch', [
                    'invoice' => $invoice->number,
                    'expected' => (string) $invoice->total,
                    'received' => (string) $transaction->amount,
                ]);

                continue;
            }

            try {
                $this->reconciliation->reconcileWithInvoice($transaction, $invoice);
                $matched++;
            } catch (\Throwable $e) {
                Log::warning('QrPaymentMatching: could not reconcile', [
                    'transaction_id' => $transaction->id,
                    'invoice_id' => $invoice->id,
                    'error' => $e->getMessage(),
                ]);

                $needsReview[] = __('app.automation_qr_failed', ['invoice' => $invoice->number]);
            }
        }

        return AutomationResult::withFindings(
            __('app.automation_qr_matched', ['count' => $matched]),
            $needsReview,
            ['matched' => $matched, 'needs_review' => count($needsReview)],
        );
    }
}
